//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ctrip.SOA.Service.Test.UserService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserService.IUserService")]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/AddUser", ReplyAction="http://tempuri.org/IUserService/AddUserResponse")]
        Ctrip.SOA.Bussiness.User.DataContract.UserModelResponse AddUser(Ctrip.SOA.Bussiness.User.DataContract.UserModelRequest entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdateUser", ReplyAction="http://tempuri.org/IUserService/UpdateUserResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ctrip.SOA.Bussiness.User.DataContract.UserModelResponse))]
        Ctrip.SOA.Infratructure.ServiceProxy.BaseResponse UpdateUser(Ctrip.SOA.Bussiness.User.DataContract.UserModelRequest entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/DeleteUser", ReplyAction="http://tempuri.org/IUserService/DeleteUserResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ctrip.SOA.Bussiness.User.DataContract.UserModelResponse))]
        Ctrip.SOA.Infratructure.ServiceProxy.BaseResponse DeleteUser(Ctrip.SOA.Bussiness.User.DataContract.UserModelRequest entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetAllUsers", ReplyAction="http://tempuri.org/IUserService/GetAllUsersResponse")]
        Ctrip.SOA.Bussiness.User.DataContract.UserModelResponse[] GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUser", ReplyAction="http://tempuri.org/IUserService/GetUserResponse")]
        Ctrip.SOA.Bussiness.User.DataContract.UserModelResponse GetUser(Ctrip.SOA.Bussiness.User.DataContract.UserModelRequest entity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : Ctrip.SOA.Service.Test.UserService.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<Ctrip.SOA.Service.Test.UserService.IUserService>, Ctrip.SOA.Service.Test.UserService.IUserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Ctrip.SOA.Bussiness.User.DataContract.UserModelResponse AddUser(Ctrip.SOA.Bussiness.User.DataContract.UserModelRequest entity) {
            return base.Channel.AddUser(entity);
        }
        
        public Ctrip.SOA.Infratructure.ServiceProxy.BaseResponse UpdateUser(Ctrip.SOA.Bussiness.User.DataContract.UserModelRequest entity) {
            return base.Channel.UpdateUser(entity);
        }
        
        public Ctrip.SOA.Infratructure.ServiceProxy.BaseResponse DeleteUser(Ctrip.SOA.Bussiness.User.DataContract.UserModelRequest entity) {
            return base.Channel.DeleteUser(entity);
        }
        
        public Ctrip.SOA.Bussiness.User.DataContract.UserModelResponse[] GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public Ctrip.SOA.Bussiness.User.DataContract.UserModelResponse GetUser(Ctrip.SOA.Bussiness.User.DataContract.UserModelRequest entity) {
            return base.Channel.GetUser(entity);
        }
    }
}
